/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import PromoOpen from "./TJ/Promo/script/PromoOpen"
import ButtonScale from "./TJ/Promo/script/ButtonScale"
import PromoItem from "./TJ/Promo/script/PromoItem"
import P201 from "./TJ/Promo/script/P201"
import P202 from "./TJ/Promo/script/P202"
import P103 from "./TJ/Promo/script/P103"
import P204 from "./TJ/Promo/script/P204"
import P205 from "./TJ/Promo/script/P205"
import P106 from "./TJ/Promo/script/P106"
import UIDefeated from "./script/Game/UIDefeated"
import UILoding from "./script/Game/UILoding"
import UIPifuTry from "./script/Game/UIPifuTry"
import UIPifu from "./script/Game/UIPifu"
import UISet from "./script/Game/UISet"
import UIStart from "./script/Game/UIStart"
import UITask from "./script/Game/UITask"
import UIVictory from "./script/Game/UIVictory"
import UIXDpifu from "./script/Game/UIXDpifu"
import HintPre from "./script/Game/HintPre"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=720;
    static height:number=1280;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="sys/UILoding.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("TJ/Promo/script/PromoOpen.ts",PromoOpen);
        reg("TJ/Promo/script/ButtonScale.ts",ButtonScale);
        reg("TJ/Promo/script/PromoItem.ts",PromoItem);
        reg("TJ/Promo/script/P201.ts",P201);
        reg("TJ/Promo/script/P202.ts",P202);
        reg("TJ/Promo/script/P103.ts",P103);
        reg("TJ/Promo/script/P204.ts",P204);
        reg("TJ/Promo/script/P205.ts",P205);
        reg("TJ/Promo/script/P106.ts",P106);
        reg("script/Game/UIDefeated.ts",UIDefeated);
        reg("script/Game/UILoding.ts",UILoding);
        reg("script/Game/UIPifuTry.ts",UIPifuTry);
        reg("script/Game/UIPifu.ts",UIPifu);
        reg("script/Game/UISet.ts",UISet);
        reg("script/Game/UIStart.ts",UIStart);
        reg("script/Game/UITask.ts",UITask);
        reg("script/Game/UIVictory.ts",UIVictory);
        reg("script/Game/UIXDpifu.ts",UIXDpifu);
        reg("script/Game/HintPre.ts",HintPre);
    }
}
GameConfig.init();